executor: LocalExecutor

config:
  core:
    load_examples: "False"
  database:
    sql_alchemy_conn: postgresql+psycopg2://airflow:airflow@postgres-postgresql.default.svc.cluster.local:5432/airflow

postgresql:
  enabled: false   # IMPORTANT : on utilise notre Postgres existant

webserver:
  service:
    type: NodePort

scheduler:
  replicas: 1

workers:
  enabled: false   # inutile avec LocalExecutor

triggerer:
  enabled: true
