env:
  email: admin@localhost.io
  password: admin
  variables:
    - name: PGADMIN_LISTEN_ADDRESS
      value: "0.0.0.0"
    - name: PGADMIN_LISTEN_PORT
      value: "80"

persistentVolume:
  enabled: true
  size: 5Gi